library(usethis)
use_git_config(user.name = "SirMassetti", user.email = "daniele.raffo@studio.unibo.it")
edit_git_config()
use_git()
create_github_token()
library(gitcreds)
gitcreds_set()
use_github()
